server:
  port: 8081
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
      
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false

client:
  url:
    cpf-validator: https://user-info.herokuapp.com/
